version: "3"

services:
  ajudai_web:
    container_name: ajudai_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      ajudai_db:
        condition: service_healthy
    networks:
      - ajudai_network

  ajudai_db:
    image: postgres:12
    container_name: ajudai_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ajudai_db
      - POSTGRES_PORT=5432
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ../postgresql/data/ajudai:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    expose:
      - 5555
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} -p $${POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ajudai_network

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
   # restart: unless-stopped
    command:
      - "http"
      - "ajudai_web:8000"
      - "--domain=grossly-ideal-giraffe.ngrok-free.app"
    ports:
      - 4040:4040
    depends_on:
      - ajudai_web
    networks:
      - ajudai_network
    environment:
      - DOMAIN=grossly-ideal-giraffe.ngrok-free.app
      - NGROK_AUTHTOKEN=2X4f4FEqdjckKwTHscARKQYCZ6s_5HrnKf4kGzAknE1kHJe1r

networks:
  ajudai_network:
    name: ajudai_network
    external: false