# Generated by Django 4.2.25 on 2025-11-04 18:39

import ajudai_django_app.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email_confirmation_token', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(default='', max_length=60)),
                ('company_name', models.CharField(default='', max_length=60)),
                ('cell_phone', models.CharField(default='99999999999', max_length=20, validators=[django.core.validators.RegexValidator(message='Favor digitar seu telefone da seguinte forma: seu DDD seguido do seu número, por exemplo: 11987654321', regex='^\\d{10,11}$')])),
                ('segmento', models.CharField(default='', max_length=60)),
                ('cargo_atual', models.CharField(default='', max_length=60)),
                ('user_plan', models.CharField(choices=[('free_user', 'Usuário em teste gratuito'), ('premium_user', 'Usuário Premium'), ('admin_user', 'Usuário Administrador')], default='free_user', max_length=40)),
                ('user_usage_payment_method_status', models.CharField(choices=[('payment_method_not_registered', 'Método de pagamento ainda não registrado'), ('payment_method_registered_ok', 'Método de pagamento registrado'), ('payment_method_failed', 'Método de pagamento falhou')], default='payment_method_not_registered', max_length=40)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('stripe_id', models.CharField(blank=True, max_length=50, null=True)),
                ('conversation_limit_set_by_user', models.DecimalField(decimal_places=2, default=5000.0, max_digits=7)),
                ('limit_on', models.BooleanField(default=False)),
                ('valor_em_debito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('chatbots_on', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_chatbot', models.CharField(default='sem nome', max_length=40)),
                # Use TextField for large free-text fields to avoid MySQL VARCHAR limits
                ('aditional_intructions', models.TextField(default='')),
                ('cardapio', models.TextField(default='')),
                ('descricao_funcao_cardapio', models.CharField(default='Obtém uma informação específica, ou um conjunto de informações específicas contidas no cardápio, como nome do produto, tamanho, ingredientes e preço', max_length=1000)),
                ('whatsapp_number', models.CharField(default='99999999999', max_length=20, validators=[django.core.validators.RegexValidator(message='Favor digitar seu telefone da seguinte forma: seu DDD seguido do seu número, por exemplo: 11987654321', regex='^\\d{10,11}$')])),
                ('whats_app_api_auth_token', models.CharField(max_length=300)),
                ('facebook_page_id', models.CharField(max_length=120)),
                ('creation_date', models.DateField(default=ajudai_django_app.models.current_date_sao_paulo)),
                ('creation_time', models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo)),
                ('chatbot_has_products_catalog', models.BooleanField(default=False)),
                ('catalog_id', models.CharField(default='', max_length=255)),
                ('sections_and_products', models.JSONField(default=dict)),
                ('resposta_aparencia_antes_lista_produtos', models.CharField(default='Itens do Pedido (considerar estes e desconsiderar os anteriores): ', max_length=10000)),
                ('resposta_pedido_catálogo', models.CharField(default='Itens pedidos registrados com sucesso. Agora, para concluirmos o seu pedido, pedimos para informar se você quer retirar o seu pedido no balcão ou que ele seja entregue para você', max_length=10000)),
                ('initial_message_text', models.CharField(default='Olá, seja bem-vindo! Veja nosso cardápio e selecione os itens que você deseja os adicionando no carrinho:', max_length=10000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=ajudai_django_app.models.current_date_sao_paulo)),
                ('creation_time', models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo)),
                ('date', models.DateField(default=ajudai_django_app.models.current_date_sao_paulo)),
                ('time', models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo)),
                ('context', models.JSONField(default=list)),
                ('messages_display_time', models.JSONField(default=list)),
                ('company_client_number', models.CharField(max_length=20)),
                ('total_tokens_used', models.PositiveIntegerField(default=0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('numero_do_pedido_gerado_com_a_conversa', models.PositiveIntegerField(default=0)),
                ('status_da_conversa', models.CharField(choices=[('conversa_em_andamento', 'Conversa em andamento'), ('conversa_encerra_tempo_sem_pedido', 'Conversa encerrada'), ('conversa_falhou', 'Conversa encerrada (falha)')], default='conversa_em_andamento', max_length=120)),
                ('financial_status', models.CharField(choices=[('paga', 'Conversa Paga'), ('pendente', 'Pagamento Pendente'), ('aguardando_vencimento', 'Conversa Aguardando Vencimento Para Ser Cobrada')], default='aguardando_vencimento', max_length=70)),
                ('chatbot_ativo', models.BooleanField(default=True)),
                ('last_message_shown', models.BooleanField(default=False)),
                ('need_refresh_view', models.BooleanField(default=False)),
                ('chatbot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajudai_django_app.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('VIP', 'Corporativo VIP'), ('adesao', 'Adesão')], default='Basic', max_length=32)),
                ('tipo_de_produto', models.CharField(choices=[('adesao', 'Adesão'), ('conversa_avulsa', 'Conversa Aulsa')], default='conversa_avulsa', max_length=30)),
                ('ai_api_provider', models.CharField(choices=[('open_ai', 'Open AI')], default='', max_length=120)),
                ('ai_model_name', models.CharField(choices=[('gpt-4o-2024-11-20', 'GPT-4o')], default='', max_length=120)),
                ('free_use_limit_conversations', models.PositiveIntegerField(default=0)),
                ('priceID', models.CharField(default='', max_length=120)),
                ('currency', models.CharField(choices=[('BRL', 'Reais (R$)')], default='BRL', max_length=3)),
                ('price_shown', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('minimo_conversas', models.PositiveIntegerField(default=0)),
                ('maximo_conversas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Premium_User_Payment_Method_Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=ajudai_django_app.models.current_date_sao_paulo)),
                ('time', models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo)),
                ('stripe_checkout_id', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('payment_method_pending', 'Pending Payment Method'), ('payment_method_success', 'Approved Payment Method'), ('payment_method_failing', 'Rejected Paging Method. Please change it to continue using the services')], default='payment_method_pending', max_length=50)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_manualmente', models.BooleanField(default=False)),
                ('nome_pedido_manual', models.CharField(default='', max_length=120)),
                ('status_do_pedido', models.CharField(choices=[('pedido_realizado_manual', 'Pedido realizado'), ('pedido_em_processo', 'Pedido em processo'), ('pendente_de_entrega', 'Pendente de Entrega'), ('entregue', 'Pedido Entregue'), ('cancelado', 'Pedido Cancelado')], default='pedido_realizado_manual', max_length=120)),
                # Very long summary: use TextField for MySQL compatibility
                ('resumo_do_pedido', models.TextField(default='')),
                ('date', models.DateField(default=ajudai_django_app.models.current_date_sao_paulo)),
                ('time', models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo)),
                ('nome_do_cliente', models.CharField(default='', max_length=60)),
                ('cpf_do_cliente', models.CharField(default='', max_length=60)),
                ('data_de_agendamento', models.CharField(default='', max_length=60)),
                ('email_do_cliente', models.CharField(default='', max_length=60, null=True)),
                ('itens_pedido', models.CharField(default='', max_length=12000)),
                ('endereco_entrega', models.CharField(default='', max_length=200)),
                ('taxa_de_entrega', models.CharField(default='', max_length=60)),
                ('valor_total', models.CharField(default='', max_length=60)),
                ('mostrar_kanban', models.BooleanField(default=True)),
                ('conversa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajudai_django_app.conversa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsForUseMadde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=ajudai_django_app.models.current_date_sao_paulo)),
                ('time', models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo)),
                ('product_name', models.CharField(default='Basic', max_length=120)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('status', models.CharField(choices=[('fatura_paga', 'Pagamnento confirmado'), ('fatura_pendente', 'Aguardando confirmação')], default='fatura_pendente', max_length=120)),
                ('numero_conversas', models.PositiveIntegerField(default=0)),
                ('valor_total', models.CharField(default='R$0,00', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DadosClienteCadatrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=60)),
                ('cpf', models.CharField(default='', max_length=60)),
                ('data_1', models.CharField(default='', max_length=60)),
                ('email_1', models.CharField(default='', max_length=60, null=True)),
                ('endereco', models.CharField(default='', max_length=60)),
                ('telefone', models.CharField(default='', max_length=20)),
                ('metodo_pagamento', models.CharField(default='', max_length=60)),
                ('ultima_conversa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajudai_django_app.conversa')),
            ],
        ),
        migrations.CreateModel(
            name='Adesao_Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo)),
                ('stripe_checkout_id', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('payment_method', models.CharField(choices=[('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto'), ('pix', 'Pix'), ('outro', 'Outro')], default='cartao_credito', max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajudai_django_app.product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
