# Generated by Django 4.2.1 on 2023-05-10 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cargo_atual',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cell_phone',
            field=models.CharField(default='99999999999', validators=[django.core.validators.RegexValidator(message='Favor digitar seu telefone da seguinte forma: seu DDD seguido do seu número', regex='^\\d{10,11}$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='customuser',
            name='segmento',
            field=models.CharField(default='', max_length=60),
        ),
    ]
