# Generated by Django 4.2.1 on 2023-05-12 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0002_customuser_cargo_atual_customuser_cell_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aditional_intructions', models.CharField(default='', max_length=15564)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Conversa Finalizada', max_length=32)),
                ('ai_api_provider', models.CharField(choices=[('open_ai', 'Open AI')], default='', max_length=120)),
                ('ai_model_name', models.CharField(choices=[('gpt-3.5-turbo', 'GPT 3.5')], default='', max_length=120)),
                ('capacity_level', models.CharField(default='', max_length=32)),
                ('free_use_limit_conversations', models.PositiveIntegerField(default=0)),
                ('priceID', models.CharField(default='', max_length=120)),
                ('currency', models.CharField(choices=[('BRL', 'Reais (R$)')], default='BRL', max_length=3)),
                ('price_shown', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Conversas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('total_tokens_used', models.PositiveIntegerField(default=0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('numero_do_pedido_gerado_com_a_conversa', models.PositiveIntegerField(default=0)),
                ('resumo_do_pedido_gerado_com_a_conversa', models.CharField(default='')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajudai_django_app.chatbots')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatbots',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajudai_django_app.products'),
        ),
        migrations.AddField(
            model_name='chatbots',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
