# Generated by Django 4.2.1 on 2023-05-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0003_chatbots_products_conversas_chatbots_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatBots',
            new_name='ChatBot',
        ),
        migrations.RenameModel(
            old_name='Conversas',
            new_name='Conversa',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
