# Generated by Django 4.2.1 on 2023-05-12 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0004_rename_chatbots_chatbot_rename_conversas_conversa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='whatsapp_number',
            field=models.CharField(default='99999999999', validators=[django.core.validators.RegexValidator(message='Favor digitar seu telefone da seguinte forma: seu DDD seguido do seu número', regex='^\\d{10,11}$')]),
        ),
    ]
