# Generated by Django 4.2.1 on 2023-05-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0005_chatbot_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversa',
            name='user',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='facebook_page_id',
            field=models.CharField(default=13243566865, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='whats_app_api_auth_token',
            field=models.CharField(default=1324463567, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversa',
            name='company_client_number',
            field=models.CharField(default=99999999999, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversa',
            name='context',
            field=models.JSONField(default=list),
        ),
    ]
