# Generated by Django 4.2.1 on 2023-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0007_conversa_status_da_conversa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='status_da_conversa',
            field=models.CharField(choices=[('conversa_em_andamento', 'Conversa em andamento'), ('conversa_pedido_realizado', 'Conversa encerrada com pedido realizado'), ('conversa_falhou', 'Conversa encerrada por falha')], default='conversa_em_andamento', max_length=120),
        ),
    ]
