# Generated by Django 4.2.1 on 2023-05-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0008_alter_conversa_status_da_conversa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='capacity_level',
        ),
    ]
