# Generated by Django 4.2.1 on 2023-05-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0009_remove_product_capacity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='product',
        ),
    ]
