# Generated by Django 4.2.1 on 2023-05-18 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0010_remove_chatbot_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='whatsapp_number',
            field=models.CharField(default='99999999999', validators=[django.core.validators.RegexValidator(message='Favor digitar seu telefone da seguinte forma: seu DDD seguido do seu número, por exemplo: 11987654321', regex='^\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cell_phone',
            field=models.CharField(default='99999999999', validators=[django.core.validators.RegexValidator(message='Favor digitar seu telefone da seguinte forma: seu DDD seguido do seu número, por exemplo: 11987654321', regex='^\\d{10,11}$')]),
        ),
    ]
