# Generated by Django 4.2.1 on 2023-05-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0011_alter_chatbot_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='nome_do_chatbot',
            field=models.CharField(default='sem nome', max_length=40),
        ),
    ]
