# Generated by Django 4.2.1 on 2023-05-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0012_chatbot_nome_do_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='whats_app_api_auth_token',
            field=models.CharField(max_length=300),
        ),
    ]
