# Generated by Django 4.2.1 on 2023-05-19 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0013_alter_chatbot_whats_app_api_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
