# Generated by Django 4.2.1 on 2023-05-20 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0015_alter_conversa_chatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversa',
            name='resumo_do_pedido_gerado_com_a_conversa',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_do_pedido', models.CharField(choices=[('pendente_de_entrega', 'Pendente de Entrega'), ('entregue', 'Pedido Entregue'), ('cancelado', 'Pedido Cancelado')], default='pendente_de_entrega', max_length=120)),
                ('resumo_do_pedido', models.CharField(default='')),
                ('conversa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajudai_django_app.conversa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
