# Generated by Django 4.2.1 on 2023-05-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0016_remove_conversa_resumo_do_pedido_gerado_com_a_conversa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='company_client_number',
            field=models.CharField(max_length=20),
        ),
    ]
