# Generated by Django 4.2.1 on 2023-06-05 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0017_alter_conversa_company_client_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='creation_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
