# Generated by Django 4.2.1 on 2023-06-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0018_chatbot_creation_date_chatbot_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_plan',
            field=models.CharField(choices=[('free_user', 'Sem Plano Pago Ativo'), ('standard_user', 'Standart'), ('plus_user', 'Plus'), ('premium_user', 'Premium'), ('corporate_user', 'Corporativo VIP')], default='free_user', max_length=40),
        ),
    ]
