# Generated by Django 4.2.1 on 2023-06-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0019_customuser_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='limite_conversas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tipo_de_produto',
            field=models.CharField(choices=[('plan', 'Plano de Usuário'), ('adesao', 'Adesão'), ('conversa_avulsa', 'Conversa Aulsa')], default='', max_length=30),
        ),
    ]
