# Generated by Django 4.2.1 on 2023-06-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0020_customuser_last_payment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='limite_conversas',
            new_name='maximo_conversas',
        ),
        migrations.AddField(
            model_name='product',
            name='minimo_conversas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_plan',
            field=models.CharField(choices=[('free_user', 'Usuário em teste gratuito'), ('premium_user', 'Usuário Premium')], default='free_user', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='tipo_de_produto',
            field=models.CharField(choices=[('adesao', 'Adesão'), ('conversa_avulsa', 'Conversa Aulsa')], default='conversa_avulsa', max_length=30),
        ),
    ]
