# Generated by Django 4.2.1 on 2023-06-13 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0022_customuser_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='moneatry_limit_set_by_user',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=7),
        ),
        migrations.CreateModel(
            name='Premium_User_Payment_Method_Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('stripe_checkout_id', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('payment_method_pending', 'Pending Payment Method'), ('payment_method_success', 'Approved Payment Method'), ('payment_method_pending', 'Rejected Paging Method. Please change it to continue using the services')], default='payment_method_pending', max_length=50)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
