# Generated by Django 4.2.1 on 2023-06-13 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0023_customuser_moneatry_limit_set_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='financial_status',
            field=models.CharField(choices=[('paga', 'Conversa Paga'), ('pendente', 'Pagamento Pendente'), ('aguardando_vencimento', 'Conversa Aguardando Vencimento Para Ser Cobrada')], default='aguardando_vencimento', max_length=70),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_usage_payment_method_status',
            field=models.CharField(choices=[('payment_method_not_registered', 'Método de pagamento ainda não registrado'), ('payment_method_registered_ok', 'Método de pagamento registrado'), ('payment_method_failed', 'Método de pagamento falhou')], default='payment_method_not_registered', max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='moneatry_limit_set_by_user',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=7),
        ),
        migrations.CreateModel(
            name='Adesao_Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('stripe_checkout_id', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajudai_django_app.product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
