# Generated by Django 4.2.1 on 2023-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0024_conversa_financial_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
