# Generated by Django 4.2.1 on 2023-06-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0025_alter_customuser_last_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='valor_em_debito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
