# Generated by Django 4.2.1 on 2023-06-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0026_customuser_valor_em_debito'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='chatbot_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
