# Generated by Django 4.2.1 on 2023-06-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0027_conversa_chatbot_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='last_message_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='premium_user_payment_method_registration',
            name='status',
            field=models.CharField(choices=[('payment_method_pending', 'Pending Payment Method'), ('payment_method_success', 'Approved Payment Method'), ('payment_method_failing', 'Rejected Paging Method. Please change it to continue using the services')], default='payment_method_pending', max_length=50),
        ),
    ]
