# Generated by Django 4.2.1 on 2023-06-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0028_conversa_last_message_shown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='refreshed_view',
            field=models.BooleanField(default=True),
        ),
    ]
