# Generated by Django 4.2.1 on 2023-06-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0029_conversa_refreshed_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversa',
            name='refreshed_view',
        ),
        migrations.AddField(
            model_name='conversa',
            name='need_refresh_view',
            field=models.BooleanField(default=False),
        ),
    ]
