# Generated by Django 4.2.1 on 2023-06-28 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0030_remove_conversa_refreshed_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conversa',
            name='creation_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='status_da_conversa',
            field=models.CharField(choices=[('conversa_em_andamento', 'Conversa em andamento'), ('conversa_pedido_realizado', 'Conversa encerrada com pedido realizado'), ('conversa_encerra_tempo_sem_pedido', 'Conversa encerrada por tempo maior que limite ou por inatividade'), ('conversa_falhou', 'Conversa encerrada por falha')], default='conversa_em_andamento', max_length=120),
        ),
    ]
