# Generated by Django 4.2.1 on 2023-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0031_conversa_creation_date_conversa_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='messages_display_time',
            field=models.JSONField(default=list),
        ),
    ]
