# Generated by Django 4.2.1 on 2023-06-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0032_conversa_messages_display_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='status_da_conversa',
            field=models.CharField(choices=[('conversa_em_andamento', 'Conversa em andamento'), ('conversa_pedido_realizado', 'Conversa encerrada (pedido realizado)'), ('conversa_encerra_tempo_sem_pedido', 'Conversa encerrada'), ('conversa_falhou', 'Conversa encerrada (falha)')], default='conversa_em_andamento', max_length=120),
        ),
    ]
