# Generated by Django 4.2.1 on 2023-06-29 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0033_alter_conversa_status_da_conversa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_do_pedido',
            field=models.CharField(choices=[('pedido_realizado_manual', 'Pendente realizado (manual)'), ('pedido_em_processo', 'Pendente em processo'), ('pendente_de_entrega', 'Pendente de Entrega'), ('entregue', 'Pedido Entregue'), ('cancelado', 'Pedido Cancelado')], default='pedido_em_processo', max_length=120),
        ),
    ]
