# Generated by Django 4.2.1 on 2023-06-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0034_pedido_date_pedido_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='criado_manualmente',
            field=models.BooleanField(default=False),
        ),
    ]
