# Generated by Django 4.2.1 on 2023-06-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0035_pedido_criado_manualmente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nome_pedido_manual',
            field=models.CharField(default='', max_length=120),
        ),
    ]
