# Generated by Django 4.2.1 on 2023-07-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0036_pedido_nome_pedido_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='status_da_conversa',
            field=models.CharField(choices=[('conversa_em_andamento', 'Conversa em andamento'), ('conversa_encerra_tempo_sem_pedido', 'Conversa encerrada'), ('conversa_falhou', 'Conversa encerrada (falha)')], default='conversa_em_andamento', max_length=120),
        ),
    ]
