# Generated by Django 4.2.1 on 2023-07-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0037_alter_conversa_status_da_conversa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_do_pedido',
            field=models.CharField(choices=[('pedido_realizado_manual', 'Pendido realizado'), ('pedido_em_processo', 'Pedido em processo'), ('pendente_de_entrega', 'Pendente de Entrega'), ('entregue', 'Pedido Entregue'), ('cancelado', 'Pedido Cancelado')], default='pedido_realizado_manual', max_length=120),
        ),
    ]
