# Generated by Django 4.2.1 on 2023-07-06 22:09

import ajudai_django_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0038_alter_pedido_status_do_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adesao_purchase',
            name='time',
            field=models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='creation_date',
            field=models.DateField(default=ajudai_django_app.models.current_date_sao_paulo),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='creation_time',
            field=models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='creation_date',
            field=models.DateField(default=ajudai_django_app.models.current_date_sao_paulo),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='creation_time',
            field=models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='date',
            field=models.DateField(default=ajudai_django_app.models.current_date_sao_paulo),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='time',
            field=models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='date',
            field=models.DateField(default=ajudai_django_app.models.current_date_sao_paulo),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='time',
            field=models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo),
        ),
        migrations.AlterField(
            model_name='premium_user_payment_method_registration',
            name='date',
            field=models.DateField(default=ajudai_django_app.models.current_date_sao_paulo),
        ),
        migrations.AlterField(
            model_name='premium_user_payment_method_registration',
            name='time',
            field=models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo),
        ),
    ]
