# Generated by Django 4.2.1 on 2023-07-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0039_alter_adesao_purchase_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosClienteCadatrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=60)),
                ('endereco', models.CharField(default='', max_length=60)),
                ('ultima_conversa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajudai_django_app.conversa')),
            ],
        ),
    ]
