# Generated by Django 4.2.1 on 2023-07-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0040_dadosclientecadatrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosclientecadatrado',
            name='metodo_pagamento',
            field=models.CharField(default='', max_length=60),
        ),
    ]
