# Generated by Django 4.2.1 on 2023-07-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0041_dadosclientecadatrado_metodo_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosclientecadatrado',
            name='metodo_pagamento',
        ),
    ]
