# Generated by Django 4.2.1 on 2023-07-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0042_remove_dadosclientecadatrado_metodo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosclientecadatrado',
            name='metodo_pagamento',
            field=models.CharField(default='', max_length=60),
        ),
    ]
