# Generated by Django 4.2.1 on 2023-07-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0043_dadosclientecadatrado_metodo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='cardapio',
            field=models.CharField(default='', max_length=15564),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
