# Generated by Django 4.2.1 on 2023-07-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0044_chatbot_cardapio_alter_chatbot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='descricao_funcao_cardapio',
            field=models.CharField(default='Obtém uma informação específica, ou um conjunto de informações específicas contidas no cardápio, como nome do produto, tamanho, ingredientes e preço', max_length=1000),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='descricao_informacao_solicitada_do_cardapio',
            field=models.CharField(default='A informação a ser obtida através do cardápio, por exemplo, ingredientes da pizza de mussarela, preço do refrigerante coca cola lata, preço da pizza de alho', max_length=1000),
        ),
    ]
