# Generated by Django 4.2.1 on 2023-07-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0045_chatbot_descricao_funcao_cardapio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens_pedido',
            field=models.CharField(default='', max_length=12000),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_do_cliente',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.CharField(default='', max_length=60),
        ),
    ]
