# Generated by Django 4.2.1 on 2023-07-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0046_pedido_endereco_entrega_pedido_itens_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosclientecadatrado',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
