# Generated by Django 4.2.1 on 2023-07-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0047_dadosclientecadatrado_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='moneatry_limit_set_by_user',
            new_name='conversation_limit_set_by_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='limit_on',
            field=models.BooleanField(default=False),
        ),
    ]
