# Generated by Django 4.2.1 on 2023-07-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0048_rename_moneatry_limit_set_by_user_customuser_conversation_limit_set_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chatbots_on',
            field=models.BooleanField(default=True),
        ),
    ]
