# Generated by Django 4.2.1 on 2023-07-31 22:15

import ajudai_django_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0049_customuser_chatbots_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesao_purchase',
            name='payment_method',
            field=models.CharField(choices=[('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto'), ('pix', 'Pix'), ('outro', 'Outro')], default='cartao_credito', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('VIP', 'Corporativo VIP')], default='Basic', max_length=32),
        ),
        migrations.CreateModel(
            name='PaymentsForUseMadde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=ajudai_django_app.models.current_date_sao_paulo)),
                ('time', models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo)),
                ('product_name', models.CharField(default='Basic', max_length=120)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('status', models.CharField(choices=[('fatura_paga', 'Pagamnento confirmado'), ('fatura_pendente', 'Aguardando confirmação')], default='fatura_pendente', max_length=120)),
                ('numero_conversas', models.PositiveIntegerField(default=0)),
                ('valor_total', models.CharField(default='R$0,00', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
