# Generated by Django 4.2.1 on 2023-08-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0050_adesao_purchase_payment_method_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='taxa_de_entrega',
            field=models.CharField(default='', max_length=60),
        ),
    ]
