# Generated by Django 4.2.1 on 2023-08-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0051_pedido_taxa_de_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='descricao_informacao_solicitada_do_cardapio',
        ),
    ]
