# Generated by Django 4.2.1 on 2023-08-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0052_remove_chatbot_descricao_informacao_solicitada_do_cardapio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('VIP', 'Corporativo VIP'), ('adesao', 'Adesão')], default='Basic', max_length=32),
        ),
    ]
