# Generated by Django 4.2.1 on 2023-09-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0053_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_plan',
            field=models.CharField(choices=[('free_user', 'Usuário em teste gratuito'), ('premium_user', 'Usuário Premium'), ('admin_user', 'Usuário Administrador')], default='free_user', max_length=40),
        ),
    ]
