# Generated by Django 4.2.1 on 2023-09-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0054_alter_customuser_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='body_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='catalog_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='chatbot_has_products_catalog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='footer_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='sections_and_products',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='title_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
