# Generated by Django 4.2.1 on 2023-09-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0055_chatbot_body_text_chatbot_catalog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='initial_message_text',
            field=models.CharField(default='Olá, seja bem-vindo! Veja nosso cardápio e selecione os itens que você deseja os adicionando no carrinho:', max_length=10000),
        ),
    ]
