# Generated by Django 4.2.1 on 2023-10-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0056_chatbot_initial_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='title_text',
        ),
    ]
