# Generated by Django 4.2.1 on 2023-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0057_remove_chatbot_body_text_remove_chatbot_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='resposta_pedido_catálogo',
            field=models.CharField(default='Itens pedidos registrados com sucesso. Agora, para concluirmos o seu pedido, pedimos para informar se você quer retirar o seu pedido no balcão ou que ele seja entregue para você', max_length=10000),
        ),
    ]
