# Generated by Django 4.2.1 on 2023-10-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0058_chatbot_resposta_pedido_catálogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='whatsapp_number',
        ),
    ]
