# Generated by Django 4.2.1 on 2023-10-04 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0059_remove_chatbot_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='whatsapp_number',
            field=models.CharField(default='99999999999', validators=[django.core.validators.RegexValidator(message='Favor digitar seu telefone da seguinte forma: seu DDD seguido do seu número, por exemplo: 11987654321', regex='^\\d{10,11}$')]),
        ),
    ]
