# Generated by Django 4.2.1 on 2023-10-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0060_chatbot_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='resposta_aparencia_antes_lista_produtos',
            field=models.CharField(default='Itens do Pedido (considerar estes e desconsiderar os anteriores): ', max_length=10000),
        ),
    ]
