# Generated by Django 4.2.1 on 2023-10-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0061_chatbot_resposta_aparencia_antes_lista_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mostrar_kanban',
            field=models.BooleanField(default=True),
        ),
    ]
