# Generated by Django 4.2.1 on 2023-12-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0062_pedido_mostrar_kanban'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosclientecadatrado',
            name='cpf',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cpf_do_cliente',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_do_pedido',
            field=models.CharField(choices=[('pedido_realizado_manual', 'Pedido realizado'), ('pedido_em_processo', 'Pedido em processo'), ('pendente_de_entrega', 'Pendente de Entrega'), ('entregue', 'Pedido Entregue'), ('cancelado', 'Pedido Cancelado')], default='pedido_realizado_manual', max_length=120),
        ),
    ]
