# Generated by Django 4.2.1 on 2023-12-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0063_alter_pedido_status_do_pedido'),
        ('ajudai_django_app', '0063_dadosclientecadatrado_cpf_and_more'),
    ]

    operations = [
    ]
