# Generated by Django 4.2.1 on 2023-12-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0063_dadosclientecadatrado_cpf_pedido_cpf_do_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosclientecadatrado',
            name='data_1',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='dadosclientecadatrado',
            name='email_1',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_de_agendamento',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email_do_cliente',
            field=models.CharField(default='', max_length=60, null=True),
        ),
    ]
