# Generated by Django 4.2.1 on 2023-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0064_merge_20231210_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosclientecadatrado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
