# Generated by Django 4.2.1 on 2024-01-08 23:23

import ajudai_django_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0064_dadosclientecadatrado_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosclientecadatrado',
            name='creation_date',
            field=models.DateField(default=ajudai_django_app.models.current_date_sao_paulo),
        ),
        migrations.AddField(
            model_name='dadosclientecadatrado',
            name='creation_time',
            field=models.TimeField(default=ajudai_django_app.models.current_time_sao_paulo),
        ),
    ]
