# Generated by Django 4.2.1 on 2024-01-08 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajudai_django_app', '0065_dadosclientecadatrado_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosclientecadatrado',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='dadosclientecadatrado',
            name='creation_time',
        ),
    ]
